filter:
  excluded_paths:
    - 'tests/*'

checks:
  php:
    code_rating: true
    duplication: true

build:
  project_setup:
    before:
      - php-scrutinizer-run

  environment:
    mysql: false
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    rabbitmq: false

  nodes:
    php71:
      environment:
        php: 7.1
      tests:
        override:
          -
            command: 'composer phpstan'
          -
            command: 'vendor/bin/phpunit --coverage-clover=clover-file'
            coverage:
              file: 'clover-file'
              format: 'clover'

    php72:
      environment:
        php: 7.2
      tests:
        override:
          -
            command: 'composer phpstan'
          -
            command: 'vendor/bin/phpunit --coverage-clover=clover-file'
            coverage:
              file: 'clover-file'
              format: 'clover'
